### ISSUE TITLE
rename `igraph.epi_contacts` to `as.igraph.epi_contacts`

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epicontacts#41]
As it is clearly a conversion function. I don't mind at all having the function as it is, but `as.igraph...` should be available too, especially since it will let us omit the class name so that we can call `as.igraph(x)` where `x` is an `epi_contacts` object.

**Comment by nistara** [comment]
Hi Thibaut, 
I've been facing some issues with renaming the function. Here's my workflow so far:

- Created a branch: cleanup-NR
- When I run `check` on the branch, I get the following warning:
```
	==> devtools::check(document = FALSE)
	
	Setting env vars ---------------------------------------------------------------
	CFLAGS  : -Wall -pedantic
	CXXFLAGS: -Wall -pedantic
	Building epicontacts -----------------------------------------------------------
	'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
	--no-save --no-restore --quiet CMD build '/Users/nistara/Dropbox/UC  \
	DAVIS/Projects/2016_epicontacts/epicontacts' --no-resave-data --no-manual 

	* checking for file ‘/Users/nistara/Dropbox/UC DAVIS/Projects/2016_epicontacts/epicontacts/DESCRIPTION’ ... OK
	* preparing ‘epicontacts’:
	* checking DESCRIPTION meta-information ... OK
	* installing the package to build vignettes
	* creating vignettes ... OK
	* checking for LF line-endings in source and make files
	* checking for empty or unneeded directories
	* looking to see if a ‘data/datalist’ file should be added
	* building ‘epicontacts_1.0.0.tar.gz’

	Setting env vars ---------------------------------------------------------------
	_R_CHECK_CRAN_INCOMING_ : FALSE
	_R_CHECK_FORCE_SUGGESTS_: FALSE
	Checking epicontacts -----------------------------------------------------------
	'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
	--no-save --no-restore --quiet CMD check  \
	'/var/folders/pj/1g76ddnj46l9mtcs9f8m5lxm0000gp/T//Rtmpv4G9ob/epicontacts_1.0.0.tar.gz'  \
	--as-cran --timings --no-manual 

	* using log directory ‘/Users/nistara/Dropbox/UC DAVIS/Projects/2016_epicontacts/epicontacts.Rcheck’
	* using R version 3.3.1 (2016-06-21)
	* using platform: x86_64-apple-darwin13.4.0 (64-bit)
	* using session charset: UTF-8
	* using options ‘--no-manual --as-cran’
	* checking for file ‘epicontacts/DESCRIPTION’ ... OK
	* checking extension type ... Package
	* this is package ‘epicontacts’ version ‘1.0.0’
	* checking package namespace information ... OK
	* checking package dependencies ... NOTE
	Package suggested but not available for checking: ‘covr’
	* checking if this is a source package ... OK
	* checking if there is a namespace ... OK
	* checking for executable files ... OK
	* checking for hidden files and directories ... OK
	* checking for portable file names ... OK
	* checking for sufficient/correct file permissions ... OK
	* checking whether package ‘epicontacts’ can be installed ... OK
	* checking installed package size ... OK
	* checking package directory ... OK
	* checking ‘build’ directory ... OK
	* checking DESCRIPTION meta-information ... OK
	* checking top-level files ... OK
	* checking for left-over files ... OK
	* checking index information ... OK
	* checking package subdirectories ... OK
	* checking R files for non-ASCII characters ... OK
	* checking R files for syntax errors ... OK
	* checking whether the package can be loaded ... OK
	* checking whether the package can be loaded with stated dependencies ... OK
	* checking whether the package can be unloaded cleanly ... OK
	* checking whether the namespace can be loaded with stated dependencies ... OK
	* checking whether the namespace can be unloaded cleanly ... OK
	* checking dependencies in R code ... OK
	* checking S3 generic/method consistency ... OK
	* checking replacement functions ... OK
	* checking foreign function calls ... OK
	* checking R code for possible problems ... OK
	* checking Rd files ... OK
	* checking Rd metadata ... OK
	* checking Rd line widths ... OK
	* checking Rd cross-references ... OK
	* checking for missing documentation entries ... OK
	* checking for code/documentation mismatches ... WARNING
	Codoc mismatches from documentation object 'subset.epi_contacts':
	subset.epi_contacts
	Code: function(x, node.attribute = NULL, edge.attribute = NULL, ...)
	Docs: function(x, edge.attribute = NULL, node.attribute = NULL, ...)
	Mismatches in argument names:
    Position: 2 Code: node.attribute Docs: edge.attribute
    Position: 3 Code: edge.attribute Docs: node.attribute

	* checking Rd \usage sections ... OK
	* checking Rd contents ... OK
	* checking for unstated dependencies in examples ... OK
	* checking contents of ‘data’ directory ... OK
	* checking data for non-ASCII characters ... OK
	* checking data for ASCII and uncompressed saves ... OK
	* checking installed files from ‘inst/doc’ ... OK
	* checking files in ‘vignettes’ ... OK
	* checking examples ... OK
	* checking for unstated dependencies in ‘tests’ ... OK
	* checking tests ...
	Running ‘testthat.R’ OK

	* checking for unstated dependencies in vignettes ... OK
	* checking package vignettes in ‘inst/doc’ ... OK
	* checking re-building of vignette outputs ... OK
	* DONE
	Status: 1 WARNING, 1 NOTE
	checking for code/documentation mismatches ... WARNING
	Codoc mismatches from documentation object 'subset.epi_contacts':
	subset.epi_contacts
	Code: function(x, node.attribute = NULL, edge.attribute = NULL, ...)
	Docs: function(x, edge.attribute = NULL, node.attribute = NULL, ...)
	Mismatches in argument names:
    Position: 2 Code: node.attribute Docs: edge.attribute
    Position: 3 Code: edge.attribute Docs: node.attribute


	checking package dependencies ... NOTE
	Package suggested but not available for checking: ‘covr’

	See
	‘/Users/nistara/Dropbox/UC DAVIS/Projects/2016_epicontacts/epicontacts.Rcheck/00check.log’
	for details.


	R CMD check results
	0 errors | 1 warning  | 1 note 

	R CMD check succeeded
```

- after I change the name of the `igraph.epi_contacts` function to `as.igraph.epi_contacts` (including in the vignette), and run `check`, I get a new error.

```
	==> devtools::check(document = FALSE)

	Setting env vars ---------------------------------------------------------------
	CFLAGS  : -Wall -pedantic
	CXXFLAGS: -Wall -pedantic
	Building epicontacts -----------------------------------------------------------
	'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
	--no-save --no-restore --quiet CMD build '/Users/nistara/Dropbox/UC  \
	DAVIS/Projects/2016_epicontacts/epicontacts' --no-resave-data --no-manual 

	* checking for file ‘/Users/nistara/Dropbox/UC DAVIS/Projects/2016_epicontacts/epicontacts/DESCRIPTION’ ... OK
	* preparing ‘epicontacts’:
	* checking DESCRIPTION meta-information ... OK
	* installing the package to build vignettes
	* creating vignettes ... OK
	* checking for LF line-endings in source and make files
	* checking for empty or unneeded directories
	* looking to see if a ‘data/datalist’ file should be added
	* building ‘epicontacts_1.0.0.tar.gz’

	Setting env vars ---------------------------------------------------------------
	_R_CHECK_CRAN_INCOMING_ : FALSE
	_R_CHECK_FORCE_SUGGESTS_: FALSE
	Checking epicontacts -----------------------------------------------------------
	'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
	--no-save --no-restore --quiet CMD check  \
	'/var/folders/pj/1g76ddnj46l9mtcs9f8m5lxm0000gp/T//Rtmpoe4zJl/epicontacts_1.0.0.tar.gz'  \
	--as-cran --timings --no-manual 

	* using log directory ‘/Users/nistara/Dropbox/UC DAVIS/Projects/2016_epicontacts/epicontacts.Rcheck’
	* using R version 3.3.1 (2016-06-21)
	* using platform: x86_64-apple-darwin13.4.0 (64-bit)
	* using session charset: UTF-8
	* using options ‘--no-manual --as-cran’
	* checking for file ‘epicontacts/DESCRIPTION’ ... OK
	* checking extension type ... Package
	* this is package ‘epicontacts’ version ‘1.0.0’
	* checking package namespace information ... OK
	* checking package dependencies ... NOTE
	Package suggested but not available for checking: ‘covr’
	* checking if this is a source package ... OK
	* checking if there is a namespace ... OK
	* checking for executable files ... OK
	* checking for hidden files and directories ... OK
	* checking for portable file names ... OK
	* checking for sufficient/correct file permissions ... OK
	* checking whether package ‘epicontacts’ can be installed ... OK
	* checking installed package size ... OK
	* checking package directory ... OK
	* checking ‘build’ directory ... OK
	* checking DESCRIPTION meta-information ... OK
	* checking top-level files ... OK
	* checking for left-over files ... OK
	* checking index information ... OK
	* checking package subdirectories ... OK
	* checking R files for non-ASCII characters ... OK
	* checking R files for syntax errors ... OK
	* checking whether the package can be loaded ... OK
	* checking whether the package can be loaded with stated dependencies ... OK
	* checking whether the package can be unloaded cleanly ... OK
	* checking whether the namespace can be loaded with stated dependencies ... OK
	* checking whether the namespace can be unloaded cleanly ... OK
	* checking dependencies in R code ... OK
	* checking S3 generic/method consistency ... OK
	* checking replacement functions ... OK
	* checking foreign function calls ... OK
	* checking R code for possible problems ... OK
	* checking Rd files ... OK
	* checking Rd metadata ... OK
	* checking Rd line widths ... NOTE
	Rd file 'subset.epi_contacts.Rd':
	\examples lines wider than 100 characters:
    y <- subset.epi_contacts(x, node.attribute=list("gender"="f"), edge.attribute=list("source"="funeral"))

	These lines will be truncated in the PDF manual.
	* checking Rd cross-references ... OK
	* checking for missing documentation entries ... OK
	* checking for code/documentation mismatches ... OK
	* checking Rd \usage sections ... OK
	* checking Rd contents ... OK
	* checking for unstated dependencies in examples ... OK
	* checking contents of ‘data’ directory ... OK
	* checking data for non-ASCII characters ... OK
	* checking data for ASCII and uncompressed saves ... OK
	* checking installed files from ‘inst/doc’ ... OK
	* checking files in ‘vignettes’ ... OK
	* checking examples ... ERROR
	Running examples in ‘epicontacts-Ex.R’ failed
	The error most likely occurred in:

	> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
	> ### Name: subset.epi_contacts
	> ### Title: Subset an epi_contact object by factors
	> ### Aliases: subset.epi_contacts
	> 
	> ### ** Examples
	> 
	> x <- make_epi_contacts(ebola.sim$linelist, ebola.sim$contacts,
	+ id="case.id", to="case.id", from="infector", directed=FALSE)
	> y <- subset.epi_contacts(x, node.attribute=list("gender"="f"), edge.attribute=list("source"="funeral"))
	Error: could not find function "subset.epi_contacts"
	Execution halted
	* checking for unstated dependencies in ‘tests’ ... OK
	* checking tests ...
	Running ‘testthat.R’ OK
	* checking for unstated dependencies in vignettes ...
	OK
	* checking package vignettes in ‘inst/doc’ ... OK
	* checking re-building of vignette outputs ... OK
	* DONE
	Status: 1 ERROR, 2 NOTEs
	checking examples ... ERROR
	Running examples in ‘epicontacts-Ex.R’ failed
	The error most likely occurred in:

	> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
	> ### Name: subset.epi_contacts
	> ### Title: Subset an epi_contact object by factors
	> ### Aliases: subset.epi_contacts
	> 
	> ### ** Examples
	> 
	> x <- make_epi_contacts(ebola.sim$linelist, ebola.sim$contacts,
	+ id="case.id", to="case.id", from="infector", directed=FALSE)
	> y <- subset.epi_contacts(x, node.attribute=list("gender"="f"), edge.attribute=list("source"="funeral"))
	Error: could not find function "subset.epi_contacts"
	Execution halted

	checking package dependencies ... NOTE
	Package suggested but not available for checking: ‘covr’

	checking Rd line widths ... NOTE
	Rd file 'subset.epi_contacts.Rd':
	\examples lines wider than 100 characters:
    y <- subset.epi_contacts(x, node.attribute=list("gender"="f"), edge.attribute=list("source"="funeral"))

	These lines will be truncated in the PDF manual.

	See
	‘/Users/nistara/Dropbox/UC DAVIS/Projects/2016_epicontacts/epicontacts.Rcheck/00check.log’
	for details.

	R CMD check results
	1 error  | 0 warnings | 2 notes

	R CMD check succeeded
```

- For some reason, changing the function name is causing changes in `man/get_pairwise` and `man/subset.epi_contacts` as well. 
- I remember coming across some errors using `as.igraph.epi_contacts` earlier, and that's why I'd renamed it to `igraph.epi_contacts`. I'd be gratefulf if you could help figure out what's going on!

**Comment by vpnagraj** [comment]
@nistara i ran devtools::check() on my local version and was actually getting a similar error ... i think it may have something to do with the example in subset.epi_contacts(). I've changed the doc for that to use "\dontrun" around the examples and now am not getting the error. 

Try fetching the cleanup (not cleanup-NR) branch and making your changes locally, then pushing back to cleanup (not cleanup-NR). Also, I'm not sure if each of us should be making our own cleanup branches. If we want to manage it that way, then maybe it makes more sense to use forks instead of branches? @thibautjombart what do you think?

**Comment by finlaycampbell** [comment]
Hi all, 
I was also having problems with the devtools::check() and the example in subset.epi_contacts - Thibaut suggested updating devtools to fix it! Cheers, 
Finlay
On 18 Oct 2016 2:46 p.m., VP Nagraj <notifications@github.com> wrote:@nistara i ran devtools::check() on my local version and was actually getting a similar error ... i think it may have something to do with the example in subset.epi_contacts(). I've changed the doc for that to use "\dontrun" around the examples and now am not getting the error. 

Try fetching the cleanup (not cleanup-NR) branch and making your changes locally, then pushing back to cleanup (not cleanup-NR). Also, I'm not sure if each of us should be making our own cleanup branches. If we want to manage it that way, then maybe it makes more sense to use forks instead of branches? @thibautjombart what do you think?

**Comment by thibautjombart** [comment]
Hi guys

sorry, at a workshop.. 
`subset` is not exported due to a bug in devtools's old version. Update should solve it. 
As for the codoc mismatch, you need to regenerate the doc using `devtools::document`.
In general examples which fail should not be `\dontrun`'ed ;) I know it is temporary, but the risk is we'll just forget about the issue.

**Comment by vpnagraj** [comment]
So I tried updating devtools (both from cran and latest dev version on gh) but was still getting the error. I checked the NAMESPACE and noticed that "subset.epi_contacts" was not exported but "subset, epicontacts" was. I've removed the "dontrun" from the example and changed it to use `subset(x ...)` instead of `subset.epi_contacts(x ...)` and now am not getting the error on `check()`. Those changes have been pushed to the cleanup branch (34e3d13) but feel free to revert if there's a better way to manage this.

**Comment by nistara** [comment]
Thanks for the suggestions and solutions! I'll use the cleanup branch now, update devtools, and then change the function name.

**Comment by nistara** [comment]
Hi all, it's working now, and I was able to rename the function as well. Thank you for your advice and input!

**Comment by thibautjombart** [comment]
:)
